# Generated by Django 4.0.4 on 2022-05-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(default='No Bio', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.TextField(default='', max_length=1000000000),
        ),
        migrations.AlterField(
            model_name='user',
            name='profileimg',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='user',
            name='requests',
            field=models.TextField(default='', max_length=1000000000),
        ),
    ]
