# Generated by Django 4.0.4 on 2022-05-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileimg',
            field=models.FileField(blank=True, default='imgs/default-img.png', upload_to='./imgs'),
        ),
    ]
