# Generated by Django 4.0.4 on 2022-05-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileimg',
            field=models.ImageField(blank=True, default='imgs/default-img.png', upload_to='imgs/'),
        ),
    ]
