# Generated by Django 4.0.4 on 2022-05-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileimg',
            field=models.ImageField(blank=True, max_length=254, upload_to='imgs'),
        ),
    ]
