# Generated by Django 4.0.4 on 2022-05-08 04:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileimg',
            field=models.ImageField(max_length=254, storage=django.core.files.storage.FileSystemStorage(location='/imgs'), upload_to='imgs'),
        ),
    ]
