# Generated by Django 4.0.4 on 2022-05-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='usenrma', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
